### ISSUE TITLE
store dati interno

### ISSUE THREAD

**Issue by moebiusmania** [mohole/what-a-task#15]
come dicevamo l'altra sera, potete utilizzare lo stesso pattern del singleton che abbiamo usato per la classe del backend per creare un semplce store di dati interni dell'applicazione:

```javascript
'use strict';

class InternalStore {
  constructor(){
    this.data = {}
  }

  get(){
    return this.data;
  }

  set(newData){
    this.data = Object.assign({}, this.data, newData);
    return this.data;
  }
}

export const store = new InternalStore();
```

non l'ho testata ma dovrebbe funzionare, questa classe permette di scambiare dati (raggruppati in un oggetto) tra componenti indipendentemente dalla loro "distanza" nella struttura dell'applicazione, in maniera simile al setState di React.

esempio di utilizzo

```javascript
import {store} from './store.js';

store.get() // { }
store.set({ bella: 'zio'});
store.get() // { bella: 'zio' }
```

**Comment by MatteoBosi** [comment]
Grazie, l'ho provato e funziona!
